CREATE TABLE IF NOT EXISTS items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dateCreated text,
    text text,
    size text,
    thicknesses text,
    woodType text,
    deliveryDate text,
    deliveredTo text,
    "group" text,
    price integer,
    deliveredWithBox boolean
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'items'
          AND column_name = 'id'
          AND is_identity = 'NO'
    ) THEN
        ALTER TABLE items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
